#!/usr/local/bin/node
var p = require('./dst/parser');

function assertEqual( a, b ) {
    if ( a != b ) {
        throw "Expected " + a + " to equal " + b;
    }
}

assertEqual( '5', p.parse('5') );

var today = p.parse('today()');
assertEqual( 'today', today.function );
assertEqual( 0, today.parameters.length );

assertEqual( '5', p.parse('(5)').formula );

var sum = p.parse('sum(3, 1, 8)');
assertEqual( 3, sum.parameters.length );
assertEqual( '3', sum.parameters[0] );
assertEqual( '1', sum.parameters[1] );
assertEqual( '8', sum.parameters[2] );
