// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, port;

  express = require('express');

  app = express();

  app.use(express.logger());

  app.get('/', function(req, res) {
    return res.send('Hello, world!');
  });

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("listening on " + port);
  });

}).call(this);
