// Generated by CoffeeScript 1.4.0
(function() {
  var app, express, port, tester;

  tester = require('./tester');

  express = require('express');

  app = express();

  app.use(express.logger());

  app.get('/', function(req, res) {
    return res.sendfile('./example/test.html');
  });

  app.get('/test', function(req, res) {
    var data, formula;
    formula = req.query.formula;
    data = req.query.data;
    if (formula == null) {
      res.send("Formula required!");
      return;
    }
    if (!(data != null)) {
      return res.send(tester.getTemplate(formula));
    } else {
      return tester.test(formula, data, function(results) {
        return res.json(results);
      });
    }
  });

  port = process.env.PORT || 5000;

  app.listen(port, function() {
    return console.log("listening on " + port);
  });

}).call(this);
