// Generated by CoffeeScript 1.4.0
(function() {
  var csv, evaluator, getFailures, getTemplate, parser, test;

  csv = require('csv');

  parser = require('../dst/parser');

  evaluator = require('./evaluator');

  getTemplate = function(formula_src) {
    var formula, lets, tree;
    formula = parser.parse(formula_src);
    tree = evaluator.build(formula);
    lets = tree.unbound();
    lets.push('expected');
    lets.push('message');
    return lets.join(',');
  };

  test = function(formula_src, csv_src, report) {
    var formula, results;
    formula = parser.parse(formula_src);
    results = [];
    return csv().from(csv_src, {
      columns: true
    }).transform(function(data) {
      data.actual = evaluator.evaluate(formula, data);
      return data;
    }).on('record', function(data, index) {
      return results.push(data);
    }).on('end', function() {
      return report(results);
    });
  };

  getFailures = function(results) {
    var data, failures, index, message, _i, _len;
    failures = [];
    for (index = _i = 0, _len = results.length; _i < _len; index = ++_i) {
      data = results[index];
      message = "Row " + (index + 1) + ":  expected " + data.actual + " to equal " + data.expected + ".  " + data.message + ".";
      if (data.actual !== data.expected) {
        failures.push(message);
      }
    }
    return failures;
  };

  module.exports = {
    getTemplate: getTemplate,
    test: test,
    getFailures: getFailures
  };

}).call(this);
